import type { ExamplePair } from "./types";

export const EXAMPLES_DE: readonly ExamplePair[] = [
  // — Direktheit —
  { dimension: "directness", level: -2,
    before: "Ich wollte mal vorsichtig fragen, ob es vielleicht möglich wäre, den Bericht bis Freitag zu bekommen, falls das für dich passt?",
    after: "Ich brauche den Bericht bis Freitag." },
  { dimension: "directness", level: -1,
    before: "Wäre es eventuell eine Option, das Meeting zu verschieben, wenn niemand etwas dagegen hat?",
    after: "Ich möchte das Meeting verschieben. Passt Donnerstag?" },
  { dimension: "directness", level: 1,
    before: "Der Entwurf hat drei Fehler. Korrigiere sie vor dem Versand.",
    after: "Mir sind im Entwurf drei Stellen aufgefallen, die sich vor dem Versand noch lohnen würden." },
  { dimension: "directness", level: 2,
    before: "Deine Schätzung ist falsch. Es dauert doppelt so lange.",
    after: "Vielleicht übersehe ich etwas, aber ich habe das Gefühl, die Schätzung könnte etwas optimistisch sein — hättest du Lust, sie gemeinsam durchzugehen?" },
  // — Kontext —
  { dimension: "context", level: -2,
    before: "Wie beim letzten Mal, nur mit den neuen Zahlen.",
    after: "Bitte erstelle den Quartalsbericht im selben Format wie den Q2-Bericht (Excel-Vorlage im geteilten Ordner) mit den Q3-Zahlen aus der Finanztabelle." },
  { dimension: "context", level: -1,
    before: "Mach es wie üblich.",
    after: "Mach es wie üblich: Ticket anlegen, an den Support zuweisen und dem Kunden innerhalb eines Tages antworten." },
  { dimension: "context", level: 1,
    before: "Bitte öffne die Datei namens bericht-q3.xlsx im Ordner Finanzen auf dem geteilten Laufwerk, gehe zum Reiter Zusammenfassung und kopiere die Gesamtsumme aus Zelle B12.",
    after: "Bitte hol die Q3-Gesamtsumme aus dem Zusammenfassungs-Reiter." },
  { dimension: "context", level: 2,
    before: "Wie in unserem Meeting am Montag vereinbart und im Projektplan dokumentiert, ist das Deployment für die zweite Oktoberwoche geplant, also die Woche ab dem 12. Oktober.",
    after: "Das Deployment liegt wie vereinbart in der zweiten Oktoberwoche." },
  // — Soziale Nuancen —
  { dimension: "social", level: -2,
    before: "Ich hoffe, du hattest ein schönes Wochenende! Nur ganz kurz — wenn du einen Moment hast, könntest du mir die Rechnung schicken? Überhaupt keine Eile. Tausend Dank!",
    after: "Bitte schick mir die Rechnung." },
  { dimension: "social", level: -1,
    before: "Hallo! Ich hoffe, es geht dir gut. Könntest du mir bitte die Rechnung schicken, wenn du einen Moment Zeit hast? Vielen lieben Dank!",
    after: "Hallo, könntest du mir die Rechnung schicken? Danke." },
  { dimension: "social", level: 1,
    before: "Schick die Rechnung.",
    after: "Hallo, könntest du mir die Rechnung schicken? Danke." },
  { dimension: "social", level: 2,
    before: "Die Rechnung ist fällig.",
    after: "Hallo Sam, ich hoffe, deine Woche läuft gut! Wenn du einen Moment findest, könntest du mir die Rechnung zukommen lassen? Keine Eile — vielen Dank und ein schönes Wochenende!" },
  // — Semantik —
  { dimension: "semantics", level: -2,
    before: "Wir sollten nicht alles auf eine Karte setzen — halten wir einen zweiten Lieferanten im Boot.",
    after: "Wir sollten nicht von einem Lieferanten abhängen. Halten wir einen zweiten Lieferanten informiert." },
  { dimension: "semantics", level: -1,
    before: "Wir sind beim Anbieter gegen eine Wand gelaufen, deshalb hängt der Start in der Luft.",
    after: "Wir haben mit dem Anbieter keine Einigung erzielt, deshalb ist der Starttermin unsicher." },
  { dimension: "semantics", level: 1,
    before: "Wir haben mit dem Anbieter keine Einigung erzielt, deshalb ist der Starttermin unsicher.",
    after: "Wir sind beim Anbieter gegen eine Wand gelaufen, deshalb hängt der Start in der Luft." },
  { dimension: "semantics", level: 2,
    before: "Die Migration vor Abschluss der Tests zu starten ist riskant.",
    after: "Die Migration vor Abschluss der Tests zu starten ist, als würde man die Reifen bei voller Fahrt wechseln — darauf sollten wir nicht würfeln." },
];
