import type { ExamplePair } from "./types";

export const EXAMPLES_EN: readonly ExamplePair[] = [
  // — Directness —
  { dimension: "directness", level: -2,
    before: "I was wondering whether it might perhaps be possible to have the report by Friday, if that works for you?",
    after: "I need the report by Friday." },
  { dimension: "directness", level: -1,
    before: "Would it maybe be an option to move the meeting, if nobody minds?",
    after: "I'd like to move the meeting. Does Thursday work?" },
  { dimension: "directness", level: 1,
    before: "The draft has three errors. Fix them before sending.",
    after: "I noticed three things in the draft that I think are worth fixing before it goes out." },
  { dimension: "directness", level: 2,
    before: "Your estimate is wrong. It will take twice as long.",
    after: "I might be missing something, but I have a feeling the estimate could be on the optimistic side — would you be open to walking through it together?" },
  // — Context —
  { dimension: "context", level: -2,
    before: "Same as last time, just with the new numbers.",
    after: "Please prepare the quarterly report in the same format as the Q2 report (Excel template in the shared folder), using the Q3 figures from the finance sheet." },
  { dimension: "context", level: -1,
    before: "Handle it the usual way.",
    after: "Handle it the usual way: log the ticket, assign it to support, and reply to the customer within a day." },
  { dimension: "context", level: 1,
    before: "Please open the file called report-q3.xlsx in the folder named Finance on the shared drive, go to the tab named Summary, and copy the total from cell B12.",
    after: "Please grab the Q3 total from the summary tab." },
  { dimension: "context", level: 2,
    before: "As agreed in our meeting on Monday, and as documented in the project plan, the deployment is scheduled for the second week of October, which is the week starting October 12.",
    after: "Deployment is on track for the second October week, as agreed." },
  // — Social nuance —
  { dimension: "social", level: -2,
    before: "Hope you had a lovely weekend! Just a quick one — when you get a sec, could you send the invoice? No rush at all. Thanks a million!",
    after: "Please send the invoice." },
  { dimension: "social", level: -1,
    before: "Hi there! Hope all is well with you. Could you please send me the invoice when you have a moment? Thanks so much!",
    after: "Hi, could you send me the invoice? Thanks." },
  { dimension: "social", level: 1,
    before: "Send the invoice.",
    after: "Hi, could you send me the invoice? Thanks." },
  { dimension: "social", level: 2,
    before: "The invoice is due.",
    after: "Hi Sam, hope your week is going well! Whenever you get a chance, could you send over the invoice? No rush — thanks so much, and have a great weekend!" },
  // — Semantics —
  { dimension: "semantics", level: -2,
    before: "Let's not put all our eggs in one basket — we should keep a second supplier in the loop.",
    after: "We should not depend on one supplier. Let's keep a second supplier informed." },
  { dimension: "semantics", level: -1,
    before: "We hit a wall with the vendor, so the launch is up in the air.",
    after: "We could not reach an agreement with the vendor, so the launch date is uncertain." },
  { dimension: "semantics", level: 1,
    before: "We could not reach an agreement with the vendor, so the launch date is uncertain.",
    after: "We hit a wall with the vendor, so the launch is up in the air." },
  { dimension: "semantics", level: 2,
    before: "Starting the migration before the tests are done is risky.",
    after: "Starting the migration before the tests are done is like changing tyres while the car is still moving — let's not roll the dice on that." },
];
